services:
  frontend:
    container_name: layersense_frontend
    build:
      context: ./layersense_frontend
      target: dev
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./layersense_frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - agent
      - controller

  agent:
    container_name: layersense_agent
    build:
      context: ./layersense_agent
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CODESTRAL_API_KEY: ${CODESTRAL_API_KEY}
      LAYERSENSE_SCENES_DIR: /layersense_artifacts/code
    volumes:
      - ./layersense_artifacts/code:/layersense_artifacts/code

  controller:
    container_name: layersense_controller
    build:
      context: ./layersense_controller
    ports:
      - "8001:8001"
    environment:
      LAYERSENSE_SCENES_DIR: /layersense_artifacts/code
      LAYERSENSE_ARTIFACTS_DIR: /layersense_artifacts
    volumes:
      - ./layersense_artifacts/code:/layersense_artifacts/code
      - ./layersense_artifacts:/layersense_artifacts

volumes:
  frontend_node_modules:
