# docker-compose.yml
services:
  redis:
    image: redis:8.2.1
    ports:
      - 6379:6379

  # controller:
  #   build: ./controller
  #   ports: ["5000:5000"]
  #   environment:
  #     - BROKER_URL=redis://redis:6379/0
  #     - ARTIFACT_BUCKET=s3://local-minio/renders
  #   depends_on:
  #     - redis

  test:
    image: manimcommunity/manim:latest
    # build:
    #   context: ./layersense_renderer
    # environment:
    #   - BROKER_URL=redis://redis:6379/0
    # depends_on:
    #   - redis
    command: tail -f /dev/null
    volumes:
      - ./layersense_scenes:/manim:ro # read-only mount
    #   - ./layersense_artifacts:/layersense_artifacts

  # layersense_agent:
  #   build:
  #     context: ./layersense_agent
  #     dockerfile: ./layersense_agent/Dockerfile
  #   environment:
  #     - BROKER_URL=redis://redis:6379/0
  #   depends_on:
