services:
  agent:
    container_name: layersense_agent
    build:
      context: .
      dockerfile: layersense_agent/Dockerfile
      target: debug
    command:
      [
        "python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5678",
        "-m",
        "uvicorn",
        "layersense_agent.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    environment:
      PYTHONPATH: /app/layersense_agent/src:/app/layersense_domain/src
    ports:
      - "5678:5678"
    volumes:
      - ./layersense_agent/src:/app/layersense_agent/src
      - ./layersense_agent/assets:/app/layersense_agent/assets
      - ./layersense_domain/src:/app/layersense_domain/src

  controller:
    container_name: layersense_controller
    build:
      context: .
      dockerfile: layersense_controller/Dockerfile
      target: debug
    command:
      [
        "/opt/venv/bin/python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5679",
        "-m",
        "uvicorn",
        "layersense_controller.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
      ]
    environment:
      PYTHONPATH: /app/layersense_controller/src:/app/layersense_persistence/src:/app/layersense_domain/src
    ports:
      - "5679:5679"
    volumes:
      - ./layersense_controller/src:/app/layersense_controller/src
      - ./layersense_persistence/src:/app/layersense_persistence/src
      - ./layersense_domain/src:/app/layersense_domain/src

  controller-worker:
    container_name: layersense_controller_worker
    build:
      context: .
      dockerfile: layersense_controller/Dockerfile
      target: debug
    command:
      [
        "/opt/venv/bin/python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5680",
        "-m",
        "taskiq",
        "worker",
        "layersense_controller.worker:broker",
        "--workers",
        "1",
      ]
    environment:
      PYTHONPATH: /app/layersense_controller/src:/app/layersense_persistence/src:/app/layersense_domain/src
    ports:
      - "5680:5680"
    volumes:
      - ./layersense_controller/src:/app/layersense_controller/src
      - ./layersense_persistence/src:/app/layersense_persistence/src
      - ./layersense_domain/src:/app/layersense_domain/src
