WHITE: str = "#FFFFFF"
BLACK: str = "#000000"

WHITE_BACKGROUND = "#F1F6F8"

# Black to Orange
SMOKY_BLACK = "#130602"
DARK_SIENNA_A = "#250C04"
BLACK_BEAN_A = "#371206"
BLACK_BEAN_B = "#4A1708"
SEAL_BROWN = "#5C1D0A"
LIVER_ORGAN = "#6E230C"
KOBE_A = "#81290E"
KOBE_B = "#932F10"
CHINESE_RED = "#A53512"
FLAME = "#E75023"

TANGERINE = "#F98810"

# Black to Purple
XIKETIC_PURPLE = "#140009"
DARK_SIENNA_PURPLE = "#290012"
TYRIAN_PURPLE_A = "#3D001C"
TYRIAN_PURPLE_B = "#520026"
TYRIAN_PURPLE_C = "#660030"
TYRIAN_PURPLE_D = "#7A0039"

AMARANTH_PURPLE = "#B80056"

# Black to Red
XIKETIC_RED = "#110305"
DARK_SIENNA_RED = "#23060A"
RUBY_RED_A = "#34090F"
RUBY_RED_B = "#450C14"
RUBY_RED_C = "#570F19"
RUBY_RED_D = "#69121D"
RUBY_RED_E = "#7A1522"

RUSTY_RED_B = "#DA2F46"
RUSTY_RED_A = "#D0253C"

VIVID_BURGUNDY = "#990B33"
PINE_GREEN = "#157A6E"
DEFAULT_POSITIVE = PINE_GREEN
DEFAULT_NEGATIVE = VIVID_BURGUNDY

# Black to Blue
RICH_BLACK_FOGRA_A = "#06080E"
RICH_BLACK_FOGRA_B = "#0C101D"
OXFORD_BLUE_A = "#12182B"
OXFORD_BLUE_B = "#18203A"
OXFORD_BLUE_C = "#1E2848"
OXFORD_BLUE_D = "#243056"
OXFORD_BLUE_E = "#2A3865"
WILD_YONDER = "#9BA9D4"
WILD_YONDER_LIGHT = "#A9B6DB"

# Black to Light Blue
PACIFIC_BLUE_A = "#0091AD"
PACIFIC_BLUE_B = "#00AACC"
PACIFIC_BLUE_C = "#00BBE0"
PACIFIC_BLUE_D = "#00CCF5"
PACIFIC_BLUE_E = "#0AD6FF"


DEFAULT_STROKE_BLACK = SMOKY_BLACK
DEFAULT_FILL_BLACK = BLACK
DEFAULT_FILL_WHITE = WHITE
DEFAULT_INDICATE_DARK = RUBY_RED_C
DEFAULT_INDICATE_LIGHT = TYRIAN_PURPLE_D
DEFAULT_STROKE_FLASH = TYRIAN_PURPLE_B
DEFAULT_FILL_BLUE = WILD_YONDER  # OXFORD_BLUE_B
DEFAULT_INDICATE = DEFAULT_INDICATE_LIGHT
DEFAULT_SURROUNDING_DARK = OXFORD_BLUE_C
DEFAULT_SURROUNDING_LIGHT = AMARANTH_PURPLE
DEFAULT_SURROUNDING = DEFAULT_SURROUNDING_DARK

DEFAULT_EDGE_MIN = PACIFIC_BLUE_A
DEFAULT_EDGE_MAX = TANGERINE
DEFAULT_EDGE_NEUTRAL = SMOKY_BLACK


__all__ = [
    # new
    "WHITE_BACKGROUND",
    "SMOKY_BLACK",
    "DARK_SIENNA_A",
    "BLACK_BEAN_A",
    "BLACK_BEAN_B",
    "SEAL_BROWN",
    "LIVER_ORGAN",
    "KOBE_A",
    "KOBE_B",
    "CHINESE_RED",
    "FLAME",
    "XIKETIC_PURPLE",
    "DARK_SIENNA_PURPLE",
    "TYRIAN_PURPLE_A",
    "TYRIAN_PURPLE_B",
    "TYRIAN_PURPLE_C",
    "TYRIAN_PURPLE_D",
    "XIKETIC_RED",
    "DARK_SIENNA_RED",
    "RUBY_RED_A",
    "RUBY_RED_B",
    "RUBY_RED_C",
    "RUBY_RED_D",
    "RUBY_RED_E",
    "RUSTY_RED_A",
    "RUSTY_RED_B",
    "VIVID_BURGUNDY",
    "RICH_BLACK_FOGRA_A",
    "RICH_BLACK_FOGRA_B",
    "OXFORD_BLUE_A",
    "OXFORD_BLUE_B",
    "OXFORD_BLUE_C",
    "OXFORD_BLUE_D",
    "OXFORD_BLUE_E",
    "DEFAULT_STROKE_BLACK",
    "DEFAULT_FILL_BLACK",
    "DEFAULT_FILL_WHITE",
    "DEFAULT_INDICATE_DARK",
    "DEFAULT_INDICATE_LIGHT",
    "DEFAULT_STROKE_FLASH",
    "DEFAULT_FILL_BLUE",
    "DEFAULT_INDICATE",
    "DEFAULT_SURROUNDING",
    "DEFAULT_SURROUNDING_DARK",
    "DEFAULT_SURROUNDING_LIGHT",
    "WILD_YONDER",
    "WILD_YONDER_LIGHT",
    "PACIFIC_BLUE_A",
    "PACIFIC_BLUE_B",
    "PACIFIC_BLUE_C",
    "PACIFIC_BLUE_D",
    "PACIFIC_BLUE_E",
    "DEFAULT_EDGE_MIN",
    "DEFAULT_EDGE_MAX",
    "DEFAULT_EDGE_NEUTRAL",
    "DEFAULT_POSITIVE",
    "DEFAULT_NEGATIVE",
]
